<?php

/**
 * @file
 * File Table Formatter module.
 */

/**
 * Implements hook_theme().
 */
function file_table_formatter_theme() {
  return array(
    'file_table_formatter_table' => array(
      'template' => 'file-table-formatter-table',
      'variables' => array(
        'data' => NULL,
      ),
    ),
  );
}

/**
 * Preprocess for theme_file_table_formatter_table()
 * @param array $variables
 */
function template_preprocess_file_table_formatter_table(&$variables) {
  $variables['table'] = array(
    '#theme' => 'table',
    '#header' => $variables['data']->getHeader(),
    '#rows' => $variables['data']->getRows(),
  );
  $variables['title'] = $variables['data']->getTitle();
}

